# Generated by Django 3.2 on 2021-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=10000)),
                ('job_subcategory', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10000)),
                ('job_position', models.CharField(max_length=10000)),
                ('location', models.CharField(max_length=10000)),
            ],
        ),
    ]
