# Generated by Django 3.2 on 2021-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211008_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='from_cateogory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
