# Generated by Django 3.2 on 2021-10-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_job_from_cateogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='from_cateogory',
            new_name='category_from',
        ),
    ]
