# Generated by Django 3.2 on 2021-10-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_from_cateogory_job_category_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
