# Generated by Django 3.2 on 2021-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_job_category_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category_from',
            field=models.CharField(max_length=10000),
        ),
    ]
